#!/bin/bash

x-window-manager &
WM_PID=$!

/root/.vnc/start &
PID=$!

sleep 2
WND_ID=$(wmctrl -pl | awk 'NR==1 {print $1; exit}')
wmctrl -i -r $WND_ID -b add,fullscreen

wait $PID
kill -9 $(ps -s $$ -o pid=)
vncserver -kill $DISPLAY