#!/bin/bash

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

#fslview can only handle 1 image?
/usr/bin/fslview `find $INPUT_DIR -name *.nii.gz` &
pid=$!
sleep 2
#find the window id
id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
echo $id > /id.txt
wmctrl -i -r $id -b add,fullscreen

#run it for an hour
#sleep 3600
